# sync-vault.ps1
# Keeps this vault scalable: regenerates _Auto-Index.md from every NN-* module folder (recursively,
# so sub-folders like Acceptance-Criteria/ are covered) and creates a Module-Guides stub for any
# module folder that has no guide yet. Existing guides are never overwritten.
# Run whenever you add documents/modules:
#   powershell -ExecutionPolicy Bypass -File scripts\sync-vault.ps1
# Idempotent.

$vault = Split-Path $PSScriptRoot -Parent
$nl = "`n"

function To-Title([string]$s) {
  ($s -split '-' | ForEach-Object { if ($_.Length -gt 0) { $_.Substring(0,1).ToUpper() + $_.Substring(1) } }) -join ' '
}

# --- module folders at vault root (pattern: 2 digits + '-') ---
$mods = Get-ChildItem -LiteralPath $vault -Directory |
        Where-Object { $_.Name -match '^\d{2}-' } | Sort-Object Name

$sb = New-Object System.Collections.Generic.List[string]
$sb.Add("---")
$sb.Add("tags: [auto, index]")
$sb.Add("---")
$sb.Add("")
$sb.Add("# _Auto-Index (generated)")
$sb.Add("")
$sb.Add("> Generated by scripts/sync-vault.ps1. DO NOT edit by hand - it is overwritten on every sync.")
$sb.Add("> Last sync: $(Get-Date -Format 'yyyy-MM-dd HH:mm')")
$sb.Add("")
$sb.Add("## Modules")
foreach ($m in $mods) {
  $sb.Add("")
  $sb.Add("### $($m.Name)")
  Get-ChildItem -LiteralPath $m.FullName -Recurse -Filter *.md | Sort-Object FullName | ForEach-Object {
    $rel = $_.FullName.Substring($vault.Length + 1).Replace('\','/')
    $sb.Add("- [[$($rel.Substring(0, $rel.Length - 3))]]")
  }
}

# --- helper folders ---
foreach ($extra in @('Concepts','Notes','Module-Guides')) {
  $dir = Join-Path $vault $extra
  if (-not (Test-Path -LiteralPath $dir)) { continue }
  $items = @(Get-ChildItem -LiteralPath $dir -Recurse -Filter *.md | Sort-Object Name)
  if ($items.Count -eq 0) { continue }
  $sb.Add("")
  $sb.Add("## $extra")
  foreach ($it in $items) {
    $rel = $it.FullName.Substring($vault.Length + 1).Replace('\','/')
    $sb.Add("- [[$($rel.Substring(0, $rel.Length - 3))]]")
  }
}

# --- essay layer at vault root (the numbered context files) ---
$rootNotes = @(Get-ChildItem -LiteralPath $vault -Filter *.md | Where-Object { $_.Name -notmatch '^_' } | Sort-Object Name)
$sb.Add("")
$sb.Add("## Root notes")
foreach ($r in $rootNotes) { $sb.Add("- [[$($r.BaseName)]]") }

# write AFTER every section above has been appended (upstream template wrote too early and
# silently dropped the granular sections)
$autoPath = Join-Path $vault '_Auto-Index.md'
Set-Content -LiteralPath $autoPath -Value ($sb -join $nl) -Encoding UTF8
Write-Host "OK  _Auto-Index.md generated ($($mods.Count) modules, $($rootNotes.Count) root notes)" -ForegroundColor Green

# --- stub Module Guide for a new module folder ---
$guideDir = Join-Path $vault 'Module-Guides'
if (-not (Test-Path -LiteralPath $guideDir)) { New-Item -ItemType Directory -Path $guideDir | Out-Null }
$existing = @(Get-ChildItem -LiteralPath $guideDir -Filter *.md -ErrorAction SilentlyContinue)

$created = 0
foreach ($m in $mods) {
  $num = $m.Name.Substring(0,2)
  $has = $existing | Where-Object { $_.Name -match ("^" + $num + " ") }
  if (-not $has) {
    $title = To-Title ($m.Name.Substring(3))
    $stubName = "$num - $title.md"
    $st = New-Object System.Collections.Generic.List[string]
    $st.Add("---")
    $st.Add("tags: [module, $num]")
    $st.Add("---")
    $st.Add("")
    $st.Add("# $num - $title")
    $st.Add("")
    $st.Add("**Purpose:** _TODO one sentence: what a reader gets from this module._")
    $st.Add("")
    $st.Add("## Files in this module")
    Get-ChildItem -LiteralPath $m.FullName -Recurse -Filter *.md | Sort-Object FullName | ForEach-Object {
      $rel = $_.FullName.Substring($vault.Length + 1).Replace('\','/')
      $st.Add("- [[$($rel.Substring(0, $rel.Length - 3))]]")
    }
    $st.Add("")
    $st.Add("## Key facts")
    $st.Add("- _TODO_")
    Set-Content -LiteralPath (Join-Path $guideDir $stubName) -Value ($st -join $nl) -Encoding UTF8
    Write-Host "NEW guide stub: $stubName" -ForegroundColor Cyan
    $created++
  }
}
if ($created -eq 0) { Write-Host "OK  Every module already has a guide." -ForegroundColor Green }

# --- run link check ---
Write-Host ""
Write-Host "--- link check ---" -ForegroundColor DarkGray
& (Join-Path $PSScriptRoot 'check-links.ps1')
